# -*- coding: utf-8 -*-
"""YahooFinance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hfnxTY4-S_RAUsOPgnzHrOL7g-Hv_ow1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader as web

#!pip install yfinance --upgrade --no-cache-dir
import yfinance as yf
yf.pdr_override()

ibov = web.get_data_yahoo('^BVSP')

ibov.head()

ibov.tail()

ibov['High'].plot()

ibov['Close'].plot()

data = yf.download('^BVSP',start="2020-3-20", end="2020-5-22")

axes = data.plot()
axes.set_ylim([60000.000000,100000.000000])

axes = data['Close'].plot()
axes.set_ylim([60000.000000,100000.000000])

data.head(42)

start = 0
end = 1
start2 = 1
end2 = 2
date = []

while start < 41:
  minidata = data.iloc[start:end,3:4]
  minidata2 = data.iloc[start2:end2,3:4]
  arr = minidata.to_numpy()
  arrb = minidata2.to_numpy()
  result = arrb-arr
  date.append(minidata2)
  print (result)
  start+=1
  end+=1
  start2+=1
  end2+=1

data = yf.download('^NYA',start="2020-3-20", end="2020-5-22")


axes = data['Close'].plot()


start = 0
end = 1
start2 = 1
end2 = 2
date = []

while start < 41:
  minidata = data.iloc[start:end,3:4]
  minidata2 = data.iloc[start2:end2,3:4]
  arr = minidata.to_numpy()
  arr = np.round(arr, 2)
  arrb = minidata2.to_numpy()
  arrb = np.round(arrb, 2)
  result = arrb-arr
  date.append(minidata2)
  print (result)
  start+=1
  end+=1
  start2+=1
  end2+=1

data.head(42)